### ISSUE TITLE
TAXII 2.0?

### ISSUE THREAD

**Issue by arcsector** [eclecticiq/cabby#56]
Any plans for TAXII 2.0 integration? I **much** prefer cabby's interface and cli options to any of the other tools out there...

**Comment by traut** [comment]
TAXII 2.0 is on our horizon but there are no solid ETAs yet

**Comment by arcsector** [comment]
Awesome; the issue can be closed then.

**Comment by jtcotton63** [comment]
@traut any update to the timeline for TAXII 2.0 support?

**Comment by arcsector** [comment]
@jtcotton63 i noticed you also commented on oasis' taxii 2.0 server; do you have a real use case for taxii 2.0? As far as i know, no one supports it yet

**Comment by traut** [comment]
@jtcotton63 I have some thoughts on it but again, as a year ago, no strong ETA - mostly because I haven't heard any strong requirements for it from my peers / clients.

**Comment by jtcotton63** [comment]
@arcsector my use case is that my employer wants to set up their own TAXII feed, which is why I've started looking into it. I figured that 2.0 would be the best place to start since it's the most recent standard, but like you I've discovered that it has almost no adoption. For now, since 2.0 isn't well adopted, we'll probably just have to use 1.0.

**Comment by arcsector** [comment]
Sounds good. @traut I think this issue can be closed.
