### ISSUE TITLE
Http 1.1 - Unknown protocol

### ISSUE THREAD

**Issue by drorIvry** [eclecticiq/cabby#74]
Hey, I'm trying to poll from a taxii server but getting
```
2020-02-11 08:26:04,892 - ERROR   - cabby.entities:192 - Unknown service protocol: urn:taxii.mitre.org:protocol:http:1.1
```
After peaking in this line of code I've found out that you only support
 ```
'urn:taxii.mitre.org:protocol:http:1.0'
```
thank you!

**Comment by arcsector** [comment]
Are you going to close the issue?

**Comment by traut** [comment]
@drorIvry Cabby supports both TAXII 1.0 and TAXII 1.1

**Comment by drorIvry** [comment]
yes, however cabby raises an error for the following xml binding 
`'urn:taxii.mitre.org:protocol:http:1.1'`
can you add this binding to the constants so that the following error won't occur:  
`2020-02-11 08:26:04,892 - ERROR   - cabby.entities:192 - Unknown service protocol: urn:taxii.mitre.org:protocol:http:1.1
`

**Comment by arcsector** [comment]
Can you post your sample code/CLI usage and the server which you're trying to contact?

**Comment by drorIvry** [comment]
My code:

```
client = cabby.create_client(
    host=taxii_config.taxii_server,
    discovery_path=taxii_config.taxii_discovery_uri,
    port=taxii_config.taxii_port,
    use_https=taxii_config.use_https,
    headers=taxii_config.headers
 )

client.set_auth(
    cert_file=path_dict.get('client_cert'),
    key_file=path_dict.get('cert_key'),
    key_password=taxii_config.cert_key_passphrase,
    username=taxii_config.taxii_username,
    password=taxii_config.taxii_password,
    jwt_auth_url=taxii_config.taxii_jwt_auth_url,
    verify_ssl=taxii_config.verify_ssl,
    ca_cert=path_dict.get('ca_cert'),
)

for result in client.poll(
    collection_name=collection_name,
    begin_date=begin_date,
    end_date=end_date,
    subscription_id=subscription_id,
    content_bindings=content_bindings,
    uri=uri,
):
    # stuff
```

As for the server, It is a private taxii server

**Comment by traut** [comment]
@drorIvry that should create TAXII 1.1 client instance. 

I think I understand the issue now. Cabby does not support `urn:taxii.mitre.org:protocol:http:1.1`.  

Note that *protocol* bindings are different from *service* bindings. Both TAXII 1.0 and 1.1 service bindines (`urn:taxii.mitre.org:services:1.0` and `urn:taxii.mitre.org:services:1.1`) support only protocol bindings: `urn:taxii.mitre.org:protocol:http:1.0` and `urn:taxii.mitre.org:protocol:https:1.0`. That's why Cabby does not support `urn:taxii.mitre.org:protocol:http:1.1` that your server returns

**Comment by drorIvry** [comment]
thank you for your help!
